#ifndef INCLUDE_GUARD_LIBC_REPLACER_CC_INTERFACE_H_
#define INCLUDE_GUARD_LIBC_REPLACER_CC_INTERFACE_H_

#include "libc_replacer/cc/time/time.h"

#endif // INCLUDE_GUARD_LIBC_REPLACER_CC_INTERFACE_H_
