---
name: Set up environment

inputs:
  bazel-version:
    description: Bazel version
    required: true

runs:
  using: composite
  steps:
    - name: Generate .bazeliskrc
      shell: bash
      run: |
        echo "USE_BAZEL_VERSION=${{ inputs.bazel-version }}" > .bazeliskrc
    - name: Install bazelisk
      uses: yuyawk/github-actions/install-bazelisk@v1
