---
name: Run tests
on:
  push:
    branches:
      - main
  pull_request:
  schedule:
    - cron: "30 8 * * *" # runs every day at 8:30 am

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  example:
    strategy:
      matrix:
        bazel-version:
          - 6.x
          - 7.x
        runner:
          - ubuntu-20.04
          - ubuntu-22.04
    runs-on: ${{ matrix.runner }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up
        uses: ./.github/actions/setup
        with:
          bazel-version: ${{ matrix.bazel-version }}
      - name: Validate example
        shell: bash
        run: ./development/cli/validate_example.bash

  style-check:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        style-checker:
          - buildifier.bash
          - clang_format.bash
          - clang_tidy_example.bash
          - clang_tidy_root.bash
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}
      - name: Set up
        uses: ./.github/actions/setup
        with:
          bazel-version: 7.x
      - name: Run formatters and linters
        shell: bash
        run: "./development/cli/style_check/${STYLE_CHECKER}"
        env:
          STYLE_CHECKER: ${{ matrix.style-checker }}
      - name: Fail if some files are changed
        shell: bash
        run: |
          if ! git diff --exit-code; then
            echo "ERROR: Files are changed by formatters" >&2
            exit 1
          fi

  all-tests-passable:
    if: always()
    needs:
      - example
      - style-check
    runs-on: ubuntu-latest
    steps:
      - name: Decide whether the needed jobs succeeded or failed
        uses: re-actors/alls-green@release/v1
        with:
          jobs: ${{ toJSON(needs) }}
